### ISSUE TITLE
Geekbench GPU Score

### ISSUE THREAD

**Issue by cattyhouse** [Pavo-IM/AGPMInjector#1]
Hello, I have RX 560 GPU with Z77 mb and 1230 v2 CPU, using MacPro6,1 SMBIOS, tried your app to generate the AGPM kext for MacPro6,1, geek bench score dropped from 75000 to only 40000 after wake from sleep. Normal boot has no problem. 

macOS 10.14.4 beta 3
kexts installed: Lilu, whatevergreen.  PEG0 is showed as GFX0 in ioreg.

**Comment by Pavo-IM** [comment]
This has nothing to do with my app.

**Comment by cattyhouse** [comment]
> This has nothing to do with my app.

Hello, that's a fast reply. 

If i remove the kext generated, there is no geekbench benchmark drop, also tested by other users with RX 570 card.  

I use your kext because it solved my fan speed issue: 

https://www.tonymacx86.com/threads/solved-rx-560-very-high-fan-speed-after-wake-from-sleep-on-10-14-4.272090/#post-1914259

**Comment by Pavo-IM** [comment]
My app only generates the proper AGPM settings for desktop GPUs. If your GB score dropped after using using the injector kext then most likely cause is your GPU is running at higher power before using the proper power management settings. Which I have no controller of.

**Comment by cattyhouse** [comment]
i see. maybe i was not clear. 
Case 1:
1. generate the AGPM.kext, put it to clover/kexts/other
2. reboot and test geekbench OpenCL, i got score of  75000 with RX 560
3. sleep the computer, wake up and test again, I got score of 40000 with same RX 560

Case 2:
1. remove the kext from clover/kexts/other
2. reboot and run geekbench, i got score of 75000
3. sleep the computer, wake up and test again, i got the same 75000 score. 

well this is not a big problem for me as i don't play games on macOS, i only do video editing and playing. your app solved my fan speed issue while using GPU for videos on wake from sleep , i will still use it. i don't know if this has something to do with macOS 10.14.4, as i don't have fan issue before 10.14.4. 

cheers

**Comment by Pavo-IM** [comment]
This is a sleep/wake issue, not a AGPM issue.

**Comment by cattyhouse** [comment]
How to explain that without the kext, no score drop wake from sleep?
