### ISSUE TITLE
AGPM Error Boost Issue

### ISSUE THREAD

**Issue by ghost** [Pavo-IM/AGPMInjector#13]
I'm using OpenCore 0.7.2 on i5 10400 and RX580 as dGPU and UHD630 as headless iGPU. I realize that when im using SSDT-PLUG.aml (SSDTTime) x86PlatformPlugin is enable. However, i just check boot log via Hackintool which appear something called 

"[AGPM][ERROR][BOOST       ][setBoost                ] 0 fGPUIdleIntervalMS = 0, ControlID = 17"

![Screenshot 2021-08-19 at 3 50 58 PM](https://user-images.githubusercontent.com/86180725/130029631-fdaf307e-1904-42cd-933c-3835d58e276e.png)

If im using AGPMInjector.kext, this issue still exist. The problem solve if I removing SSDT-PLUG.aml but x86PlatformPlugin not enable. 
Is there any recommendation to me or any guide to fix this issue? Thank you so much. I love this Community.

**Comment by Pavo-IM** [comment]
Not sure what that error is but AGPMInjector requires x86PlatformPlugin loaded in order of it to work. Plus this app as been merged into OC Gen-X.
