### ISSUE TITLE
Support for Radeon 5600 XT

### ISSUE THREAD

**Issue by mathisschmieder** [Pavo-IM/AGPMInjector#6]
Hi there,

I'd appreciate it if you could add support for the 5600XT :)

Radeon RX 5600 XT:
  Chipset Model:	Radeon RX 5600 XT
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Total):	6 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x731f
  Revision ID:	0x00ca
  ROM Revision:	113-4E4111U-X4E
  Metal:	Supported, feature set macOS GPUFamily2 v1

If you need anything else, please let me know!

**Comment by xiao99xiao** [comment]
@mathisschmieder Radeon RX 5600 OEM/5600 XT / 5700/5700 XT share the same device id, so you could just select 5700 XT.
