### ISSUE TITLE
The generated parameters do not change with the graphics card

### ISSUE THREAD

**Issue by yandong31** [Pavo-IM/AGPMInjector#7]
My cpu is e3 1230 v2,gpu is gtx670. Operating system is 10.15.5.  I generated info.plist  by this program.  Like this:
```
                                    <key>iMac13,2</key>
				    <dict>
					<key>Vendor10deDevice1189</key>
					<dict>
						<key>AGDCEnabled</key>
						<integer>1</integer>
						<key>Heuristic</key>
						<dict>
							<key>ID</key>
							<integer>-1</integer>
						</dict>
						<key>control-id</key>
						<integer>17</integer>
						<key>max-power-state</key>
						<integer>15</integer>
						<key>min-power-state</key>
						<integer>0</integer>
					</dict>
```
I think the parameters may be a little problem. so I change the dGPU Model to generate other kext, but only the device id changed.  is this normal?

**Comment by Pavo-IM** [comment]
Yes the parameters are the same for all dGPUs, only the Model, Vendor and Device IDs will change. Working as intended.
