### ISSUE TITLE
Crash APP 

### ISSUE THREAD

**Issue by Baio1977** [Pavo-IM/AGPMInjector#8]
I have always used this App, excellent, I have Z490M Gaming X and when I go to generate the kext, the app crashes .....
SMBios IMac 20.1 + GPU Sapphire RX 590 Nitro

**Comment by Pavo-IM** [comment]
Can you provide a crash report?

**Comment by Baio1977** [comment]
[Report ERROR.zip](https://github.com/Pavo-IM/AGPMInjector/files/5275236/Report.ERROR.zip)

**Comment by Pavo-IM** [comment]
Thanks for the report and the issue has been fixed in the new release. Please open the app and Check for Updates in the menu bar of the app.

**Comment by Baio1977** [comment]
Thank you for all the effort you put into your apps, for less capable users like me.
Now it works fine.
