### ISSUE TITLE
Support for Radeon Pro WX Series

### ISSUE THREAD

**Issue by heccoder** [Pavo-IM/AGPMInjector#9]
Is it possible to add support to the WX Series? I specifically have the WX 4100 card. Thanks!

**Comment by Pavo-IM** [comment]
If you can provide the device-id of this series I can add it.

**Comment by wernervp** [comment]
According to Hackintool the DeviceID for my Radeon Pro WX 4100 is: 0x67E31002

**Comment by rowild** [comment]
thank you for that fantastic tool! – I just tried, via OC_GEN-X, to create a kext for my Radeon Pro WX 7100. The drop-down list in the app says "W 7100", but I assume that is the same, isn't it?
However, when trying to start-up Catalina, my monitor stays black.
On 10.13.6 I start Hackintool, which tells me that the GPU device ID is 0x67C41002. That number does not appear in the info.plist of the created kext. The dict section of the kext looks like this:
```xml
	<dict>
		<key>AGPM</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.apple.driver.AGPM</string>
			<key>IOClass</key>
			<string>AGPMController</string>
			<key>IONameMatch</key>
			<string>AGPMEnabler</string>
			<key>IOProviderClass</key>
			<string>IOPlatformPluginDevice</string>
			<key>Machines</key>
			<dict>
				<key>iMac17,1</key>
				<dict>
					<key>Vendor1002Device692b</key>
					<dict>
						<key>AGDCEnabled</key>
						<integer>1</integer>
						<key>Heuristic</key>
						<dict>
							<key>ID</key>
							<integer>-1</integer>
						</dict>
						<key>control-id</key>
						<integer>17</integer>
						<key>max-power-state</key>
						<integer>15</integer>
						<key>min-power-state</key>
						<integer>0</integer>
					</dict>
				</dict>
			</dict>
		</dict>
	</dict>
```
Don't know if this is of any value... Would love to know, though, how I can get my GPU working... :-)
Thanks again!
